In [1]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

data loading

In [17]:
iris = load_iris()
x = pd.DataFrame(data=iris.data, columns=iris.feature_names)

In [23]:
y=pd.DataFrame(data=iris.target, columns=['target'])

split train test

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

feature scaling

In [32]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
X_train

model training

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

prediction

In [ ]:
import numpy as np
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.values.reshape(len(y_test),1)),1))

measure

In [42]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix, accuracy_score
cm = metrics.confusion_matrix(y_test, y_pred) 
print(cm)
accuracy = metrics.accuracy_score(y_test, y_pred) 
print("Accuracy score:",accuracy)

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
Accuracy score: 0.9736842105263158


explain the error?
***Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].***

The error you received is occurring because you have set the average parameter to 'binary' in your function call to precision_score(), but your target variable has more than two classes.

In the context of evaluating classification models using metrics like precision, recall, and F1-score, the average parameter allows you to specify how to aggregate the scores across multiple classes.The average parameter specifies the type of averaging to be performed if the target variable has multiple classes. 

If you set average='binary', the function expects a binary classification problem where the target variable has only two classes. In such a case, precision is calculated for each class separately, and then the average precision across the two classes is returned.

However, if the target variable has more than two classes, you need to use a different averaging method. You can set average to one of 'micro', 'macro', or 'weighted' instead. Here's what each of these options does:

average='micro': Calculate precision globally by counting the total true positives, false positives, and false negatives across all classes, and then computing precision as TP / (TP + FP).

average='macro': Calculate precision separately for each class and return the unweighted mean of the precisions.

average='weighted': Calculate precision separately for each class and return the weighted mean of the precisions, weighted by the number of samples in each class.

When average=None (the default), the function returns the precision, recall, or F1-score for each class separately, as an array. This is useful when you want to evaluate the performance of the model on each individual class.

For example, if you have a multiclass classification problem with 3 classes (A, B, C), and you set average=None in a call to precision_score(), the function will return an array of 3 precision scores, one for each class. This allows you to see how well the model performs on each class separately.

In [47]:
precision = metrics.precision_score(y_test, y_pred,average='micro') 
print("Precision score:",precision)
recall = metrics.recall_score(y_test, y_pred, average='micro') 
print("Recall score:",recall)

Precision score: 0.9736842105263158
Recall score: 0.9736842105263158


In [48]:
precision = metrics.precision_score(y_test, y_pred,average='macro') 
print("Precision score:",precision)
recall = metrics.recall_score(y_test, y_pred, average='macro') 
print("Recall score:",recall)

Precision score: 0.9666666666666667
Recall score: 0.9791666666666666


In [49]:
precision = metrics.precision_score(y_test, y_pred,average='weighted') 
print("Precision score:",precision)
recall = metrics.recall_score(y_test, y_pred, average='weighted') 
print("Recall score:",recall)

Precision score: 0.9763157894736842
Recall score: 0.9736842105263158


In [50]:
precision = metrics.precision_score(y_test, y_pred,average=None) 
print("Precision score:",precision)
recall = metrics.recall_score(y_test, y_pred, average=None) 
print("Recall score:",recall)

Precision score: [1.  1.  0.9]
Recall score: [1.     0.9375 1.    ]
