# ad clicking

### Importing the libraries

In [110]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder

### Importing the dataset

In [111]:
df = pd.read_csv('Social_Network_Ads.csv')

In [113]:
df

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [32]:
df.head(2)

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  \
0                     68.95   35     61833.90                256.09   
1                     80.23   31     68441.85                193.77   

                        Ad Topic Line         City  Male  Country  \
0  Cloned 5thgeneration orchestration  Wrightburgh     0  Tunisia   
1  Monitored national standardization    West Jodi     1    Nauru   

             Timestamp  Clicked on Ad  
0  2016-03-27 00:53:11              0  
1  2016-04-04 01:39:02              0

In [89]:
x=df[['Daily Time Spent on Site',	'Age',	'Area Income',	'Daily Internet Usage',	'Country',	'Male']]
y=df[['Clicked on Ad']]

In [34]:
num_categories = df['Country'].nunique()
print("Number of categories:", num_categories)

Number of categories: 237


In [94]:
cl = LabelEncoder()
x['country']=cl.fit_transform(x['Country'])

C:\Users\somrita\AppData\Local\Temp\ipykernel_24944\1081392439.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['country']=cl.fit_transform(x['Country'])


In [95]:
x=x.drop(['Country'],axis='columns')

In [ ]:
X=df[['Country','Male']]
#y=df[['Clicked on Ad']]

In [38]:
y

Clicked on Ad
0                0
1                0
2                0
3                0
4                0
..             ...
995              1
996              1
997              1
998              0
999              1

[1000 rows x 1 columns]

### Splitting the dataset into the Training set and Test set

In [96]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [97]:
X_train

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  Male  \
687                     73.27   28     67301.39                216.24     1   
500                     51.56   46     63102.19                124.85     0   
332                     56.30   49     67430.96                135.24     1   
979                     70.29   31     56974.51                254.65     1   
817                     54.47   23     46780.09                141.52     0   
..                        ...  ...          ...                   ...   ...   
835                     63.11   34     63107.88                254.94     1   
192                     60.70   49     42993.48                110.57     1   
629                     73.94   26     55411.06                236.15     1   
559                     78.64   31     60283.47                235.28     1   
684                     42.06   34     43241.19                131.55     0   

     country  
687      122  
500       12  
332      151  
979      156  
817       41  
..       ...  
835      137  
192        9  
629      101  
559      153  
684      170  

[800 rows x 6 columns]

### Feature Scaling

The fit_transform method of StandardScaler calculates the mean and standard deviation of each feature and scales the features in a single step. The transform method of StandardScaler only scales the features of new, unseen data using the previously calculated mean and standard deviation values from the training data.

In [98]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
#X_train=sc.fit_transform(X_train[['Daily Time Spent on Site','Age','Area Income','Daily Internet Usage','country']])
#X_test=sc.transform(X_test[['Daily Time Spent on Site','Age','Area Income','Daily Internet Usage','country']])
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [66]:
print(X_train[0])
print(X_train[1])
print(X_train[2])
print(X_train[3])
print(X_train[4])

[ 0.53448142 -0.92842669  0.91865168  0.84125985  1.06458129  0.09401036]
[-0.82619679  1.11581557  0.60803575 -1.2505932  -0.93933644 -1.4716429 ]
[-0.52911642  1.45652261  0.928236   -1.01277338  1.06458129  0.50677349]
[ 0.34770938 -0.58771965  0.15476965  1.72043784  1.06458129  0.57793955]
[-0.64381201 -1.49627176 -0.59931429 -0.86902858 -0.93933644 -1.05887977]


In [55]:
print(X_train[0])

[ 0.53448142 -0.92842669  0.91865168  0.84125985  0.09401036]


### fitting the model

In [99]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)

f:\codes\mlenv1\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(random_state=0)

### Predicting a new result

In [100]:
x

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  Male  \
0                       68.95   35     61833.90                256.09     0   
1                       80.23   31     68441.85                193.77     1   
2                       69.47   26     59785.94                236.50     0   
3                       74.15   29     54806.18                245.89     1   
4                       68.37   35     73889.99                225.58     0   
..                        ...  ...          ...                   ...   ...   
995                     72.97   30     71384.57                208.58     1   
996                     51.30   45     67782.17                134.42     1   
997                     51.63   51     42415.72                120.37     1   
998                     55.55   19     41920.79                187.95     0   
999                     45.01   26     29875.80                178.35     0   

     country  
0        215  
1        147  
2        184  
3        103  
4         96  
..       ...  
995      116  
996       26  
997      140  
998       85  
999       28  

[1000 rows x 6 columns]

In [102]:
y_pred = classifier.predict(X_test)

In [ ]:
print(y_pred)

In [108]:
y_pred

array([0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0], dtype=int64)

### Making the Confusion Matrix

In [104]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[107   1]
 [  3  89]]


0.98

In [ ]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.values.reshape(len(y_test),1)),1))

### Visualising the Training set results

In [105]:
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_train), y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 0.25),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 0.25))
plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('salmon', 'dodgerblue')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('salmon', 'dodgerblue'))(i), label = j)
plt.title('Logistic Regression (Training set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()

f:\codes\mlenv1\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


ValueError: X has 2 features, but StandardScaler is expecting 6 features as input.

In [86]:
cn='British Indian Ocean Territory (Chagos Archipelago)'
c[0]=cl.transform(cn)
print(classifier.predict(sc.transform([['54.7','36','31087.54','118.39','1',c]])))

ValueError: y should be a 1d array, got an array of shape () instead.

In [115]:
c=pd.DataFrame([['54.7','36','31087.54','118.39','1','British Indian Ocean Territory (Chagos Archipelago)']])

In [121]:
c[6]=cl.transform(c[5])

In [122]:
c

0   1         2       3  4  \
0  54.7  36  31087.54  118.39  1   

                                                   5   6  
0  British Indian Ocean Territory (Chagos Archipe...  29

In [125]:
c=c.drop([5],axis='columns')

In [126]:
c

0   1         2       3  4   6
0  54.7  36  31087.54  118.39  1  29

In [127]:
c1=sc.transform(c)

f:\codes\mlenv1\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [128]:
c1

array([[-0.62939672, -0.01987458, -1.76009634, -1.39845807,  1.06458129,
        -1.2296783 ]])

In [129]:
print(classifier.predict(c1))

[1]


In [ ]:
cn='British Indian Ocean Territory (Chagos Archipelago)'
print(cl.transform(cn))

In [ ]:
'54.7','36','31087.54','118.39','1','British Indian Ocean Territory (Chagos Archipelago)'
